version: '3'
services:
  benchmark:
    environment:
      - HTTPBIN_HOST=nghttp2
      - GEM_HOME=/usr/local/bundle
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_SILENCE_ROOT_WARNING=1
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=20
    image: ruby:3.3
    depends_on:
      - nghttp2
    volumes:
      - ./:/home
    command:
      /home/bench.sh

  benchmark-jruby:
    environment:
      - HTTPBIN_HOST=nghttp2
      - GEM_HOME=/usr/local/bundle
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_SILENCE_ROOT_WARNING=1
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - BUNDLE_JOBS=20
    image: jruby:9.4
    depends_on:
      - nghttp2
    volumes:
      - ./:/home
    command:
      /home/bench.sh

  nghttp2:
    ports:
      - 80:80
      - 443:443
    image: registry.gitlab.com/os85/httpx/nghttp2:1
    depends_on:
      - httpbin
    volumes:
      - ./:/home
    entrypoint:
      /usr/local/bin/nghttpx
    command:
      --no-ocsp --frontend 0.0.0.0,80;no-tls --frontend 0.0.0.0,443 --backend=httpbin,8000 /home/certs/nghttp2.key /home/certs/nghttp2.cert --accesslog-file=/dev/stdout --errorlog-file=/dev/stderr

  httpbin:
    image: mccutchen/go-httpbin
    environment:
      - PORT=8000
    volumes:
      - ./:/home
